name: cdvar
channels:
  - conda-forge
  - bioconda
  - pytorch
dependencies:
  - conda-forge::python=3.8
  - pytorch::pytorch=1.12.0
  - pip:
      - biopython==1.81
      - numpy==1.22.4
      - pandas==2.0.3
      - tqdm==4.65.0
      - scipy==1.11.1
      - scikit-learn==1.3.0
      - rtdl-num-embeddings==0.0.9
      - transformers==4.18.0
      - pybedtools==0.9.0